ifndef::snippets[]
:snippets: ../../build/generated-snippets
endif::[]
= Dev Table REST API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Dev-Table-API]]
== Dev Table API

[[Hello]]
== Hello Get 요청

operation::hello[snippets = 'http-request,http-response,request-body,response-fields']

[[User]]
== User 회원가입 요청

operation::user-sign-up[snippets = 'http-request,http-response,request-body,response-fields']

== User 패스워드 불일치

operation::user-sign-up-invalid-password-check[snippets = 'http-request,http-response,request-body,response-fields']

== User email 에러

operation::user-sign-up-invalid-email[snippets = 'http-request,http-response,request-body,response-fields']

== User password 에러

operation::user-sign-up-invalid-password[snippets = 'http-request,http-response,request-body,response-fields']

== User phone-number 에러

operation::user-sign-up-invalid-phone-number[snippets = 'http-request,http-response,request-body,response-fields']

[[Waiting]]
== Waiting 생성

operation::waiting-create[snippets = 'http-request,http-response,request-body,response-fields']

== Waiting 생성 허용 범위 예외

operation::waiting-create-valid-count[snippets = 'http-request,http-response,request-body,response-fields']

== Waiting 입력 값 예외

operation::waiting-create-valid-null[snippets = 'http-request,http-response,request-body,response-fields']

== Waiting 취소

operation::waiting-cancel[snippets = 'http-request,http-response,request-body,response-fields']

== 유저 개인의 웨이팅 조회

operation::find-my-waitings[snippets = 'http-request,http-response,request-body,response-fields']